export default [
  {
    login: 'Follower 1',
    id: 37319124,
    node_id: 'MDQ6VXNlcjM3MzE5MTI0',
    avatar_url: 'https://image.flaticon.com/icons/png/512/149/149071.png',
    gravatar_id: '',
    url: 'https://api.github.com/users/follower1',
    html_url: 'https://github.com/follower1',
    followers_url: 'https://api.github.com/users/follower1/followers',
    following_url:
      'https://api.github.com/users/follower1/following{/other_user}',
    gists_url: 'https://api.github.com/users/follower1/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/follower1/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/follower1/subscriptions',
    organizations_url: 'https://api.github.com/users/follower1/orgs',
    repos_url: 'https://api.github.com/users/follower1/repos',
    events_url: 'https://api.github.com/users/follower1/events{/privacy}',
    received_events_url: 'https://api.github.com/users/follower1/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Follower 2',
    id: 31404082,
    node_id: 'MDQ6VXNlcjMxNDA0MDgy',
    avatar_url: 'https://image.flaticon.com/icons/png/512/149/149071.png',
    gravatar_id: '',
    url: 'https://api.github.com/users/follower2',
    html_url: 'https://github.com/follower2',
    followers_url: 'https://api.github.com/users/follower2/followers',
    following_url:
      'https://api.github.com/users/follower2/following{/other_user}',
    gists_url: 'https://api.github.com/users/follower2/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/follower2/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/follower2/subscriptions',
    organizations_url: 'https://api.github.com/users/follower2/orgs',
    repos_url: 'https://api.github.com/users/follower2/repos',
    events_url: 'https://api.github.com/users/follower2/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/follower2/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Follower 3',
    id: 42711367,
    node_id: 'MDQ6VXNlcjQyNzExMzY3',
    avatar_url: 'https://image.flaticon.com/icons/png/512/149/149071.png',
    gravatar_id: '',
    url: 'https://api.github.com/users/follower3',
    html_url: 'https://github.com/follower3',
    followers_url: 'https://api.github.com/users/follower3/followers',
    following_url:
      'https://api.github.com/users/follower3/following{/other_user}',
    gists_url: 'https://api.github.com/users/follower3/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/follower3/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/follower3/subscriptions',
    organizations_url: 'https://api.github.com/users/follower3/orgs',
    repos_url: 'https://api.github.com/users/follower3/repos',
    events_url: 'https://api.github.com/users/follower3/events{/privacy}',
    received_events_url: 'https://api.github.com/users/follower3/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Follower 4',
    id: 24864699,
    node_id: 'MDQ6VXNlcjI0ODY0Njk5',
    avatar_url: 'https://image.flaticon.com/icons/png/512/149/149071.png',
    gravatar_id: '',
    url: 'https://api.github.com/users/follower4',
    html_url: 'https://github.com/follower4',
    followers_url: 'https://api.github.com/users/follower4/followers',
    following_url:
      'https://api.github.com/users/follower4/following{/other_user}',
    gists_url: 'https://api.github.com/users/follower4/gists{/gist_id}',
    starred_url: 'https://api.github.com/user/follower4/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/follower4/subscriptions',
    organizations_url: 'https://api.github.com/users/follower4/orgs',
    repos_url: 'https://api.github.com/users/follower4/repos',
    events_url: 'https://api.github.com/users/follower4/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/follower4/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Folllower 5',
    id: 40670951,
    node_id: 'MDQ6VXNlcjQwNjcwOTUx',
    avatar_url: 'https://image.flaticon.com/icons/png/512/149/149071.png',
    gravatar_id: '',
    url: 'https://api.github.com/users/follower5',
    html_url: 'https://github.com/follower5',
    followers_url: 'https://api.github.com/users/follower5/followers',
    following_url:
      'https://api.github.com/users/follower5/following{/other_user}',
    gists_url: 'https://api.github.com/users/follower5/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/follower5/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/follower5/subscriptions',
    organizations_url: 'https://api.github.com/users/follower5/orgs',
    repos_url: 'https://api.github.com/users/follower5/repos',
    events_url: 'https://api.github.com/users/follower5/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/follower5/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Follower 6',
    id: 20457752,
    node_id: 'MDQ6VXNlcjIwNDU3NzUy',
    avatar_url: 'https://image.flaticon.com/icons/png/512/149/149071.png',
    gravatar_id: '',
    url: 'https://api.github.com/users/follower6',
    html_url: 'https://github.com/follower6',
    followers_url: 'https://api.github.com/users/follower6/followers',
    following_url:
      'https://api.github.com/users/cvsiraj95/following{/other_user}',
    gists_url: 'https://api.github.com/users/follower6/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/follower6/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/follower6/subscriptions',
    organizations_url: 'https://api.github.com/users/follower6/orgs',
    repos_url: 'https://api.github.com/users/follower6/repos',
    events_url: 'https://api.github.com/users/follower6/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/follower6/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Follower 7',
    id: 33715740,
    node_id: 'MDQ6VXNlcjMzNzE1NzQw',
    avatar_url: 'https://image.flaticon.com/icons/png/512/149/149071.png',
    gravatar_id: '',
    url: 'https://api.github.com/users/follower7',
    html_url: 'https://github.com/follower7',
    followers_url: 'https://api.github.com/users/follower7/followers',
    following_url:
      'https://api.github.com/users/follower7/following{/other_user}',
    gists_url: 'https://api.github.com/users/follower7/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/follower7/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/follower7/subscriptions',
    organizations_url: 'https://api.github.com/users/follower7/orgs',
    repos_url: 'https://api.github.com/users/follower7/repos',
    events_url: 'https://api.github.com/users/follower7/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/follower7/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Follower 8',
    id: 16646383,
    node_id: 'MDQ6VXNlcjE2NjQ2Mzgz',
    avatar_url: 'https://image.flaticon.com/icons/png/512/149/149071.png',
    gravatar_id: '',
    url: 'https://api.github.com/users/follower8',
    html_url: 'https://github.com/follower8',
    followers_url: 'https://api.github.com/users/follower8/followers',
    following_url:
      'https://api.github.com/users/follower8/following{/other_user}',
    gists_url: 'https://api.github.com/users/follower8/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/follower8/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/follower8/subscriptions',
    organizations_url: 'https://api.github.com/users/follower8/orgs',
    repos_url: 'https://api.github.com/users/follower8/repos',
    events_url: 'https://api.github.com/users/follower8/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/follower8/received_events',
    type: 'User',
    site_admin: false,
  },
  
];
