export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png',
  gravatar_id: '',
  url: '',
  html_url: 'https://github.com/john-smilga',
  followers_url: '',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'Name of User',
  company: 'Name of Company',
  blog: 'Url for Blog',
  location: 'Location of user',
  email: null,
  hireable: null,
  bio: 'Bio of user',
  twitter_username: 'twitter username',
  public_repos: '',
  public_gists: '',
  followers: '',
  following: '',
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
}; 

// 20210704000222
// https://api.github.com/users/rashi-agrawal29

/* 
  "login": "rashi-agrawal29",
  "id": 86194037,
  "node_id": "MDQ6VXNlcjg2MTk0MDM3",
  "avatar_url": "https://avatars.githubusercontent.com/u/86194037?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/rashi-agrawal29",
  "html_url": "https://github.com/rashi-agrawal29",
  "followers_url": "https://api.github.com/users/rashi-agrawal29/followers",
  "following_url": "https://api.github.com/users/rashi-agrawal29/following{/other_user}",
  "gists_url": "https://api.github.com/users/rashi-agrawal29/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/rashi-agrawal29/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/rashi-agrawal29/subscriptions",
  "organizations_url": "https://api.github.com/users/rashi-agrawal29/orgs",
  "repos_url": "https://api.github.com/users/rashi-agrawal29/repos",
  "events_url": "https://api.github.com/users/rashi-agrawal29/events{/privacy}",
  "received_events_url": "https://api.github.com/users/rashi-agrawal29/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": "Indore, Madhya Pradesh",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 0,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-06-20T13:40:56Z",
  "updated_at": "2021-07-02T14:57:02Z"
};
 */